const login=document.querySelector('#login'),dashboard=document.querySelector('#dashboard'),error=document.querySelector('#error');
let currentData=null;
async function api(path,options){const response=await fetch(path,options);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Error');return response.json()}
const number=value=>new Intl.NumberFormat('es-CO').format(value||0);
function list(id,rows){document.querySelector(id).innerHTML=rows?.length?rows.map(row=>`<li><span>${escapeHtml(row.label||'—')}</span><b>${number(row.count)}</b></li>`).join(''):'<li>Sin datos todavía</li>'}
function escapeHtml(value){const el=document.createElement('span');el.textContent=String(value);return el.innerHTML}
function grouped(rows,mode){const out=new Map();for(const row of rows||[]){const raw=row.period||row.day,key=mode==='year'?raw.slice(0,4):mode==='month'?raw.slice(0,7):raw,item=out.get(key)||{period:key,views:0,consultations:0,downloads:0};for(const metric of ['views','consultations','downloads'])item[metric]+=Number(row[metric]||0);out.set(key,item)}return [...out.values()]}
function draw(){const canvas=document.querySelector('#trend'),rows=grouped(currentData?.common?.trend,document.querySelector('#granularity').value),ratio=devicePixelRatio||1,width=canvas.clientWidth||900,height=260;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const pad={l:34,r:14,t:18,b:28},keys=[['views','#087fb7'],['consultations','#7c3aed'],['downloads','#16a36a']],max=Math.max(1,...rows.flatMap(row=>keys.map(([key])=>Number(row[key]||0))));ctx.strokeStyle='#e3eaf0';for(let i=0;i<5;i++){const y=pad.t+(height-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke()}for(const [key,color] of keys){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=2.5;rows.forEach((row,index)=>{const x=pad.l+(width-pad.l-pad.r)*index/Math.max(1,rows.length-1),y=height-pad.b-(height-pad.t-pad.b)*Number(row[key]||0)/max;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.fillStyle='#64748b';ctx.font='11px system-ui';ctx.fillText('0',8,height-pad.b+4);ctx.fillText(String(max),8,pad.t+4);if(rows.length){ctx.fillText(rows[0].period,pad.l,height-7);ctx.fillText(rows.at(-1).period,width-pad.r-55,height-7)}}
async function load(days=30){const data=await api(`/api/admin/overview?days=${days}`),t=data.totals||{},c=data.common||{};currentData=data;login.hidden=true;dashboard.hidden=false;document.querySelector('#warning').hidden=data.configured;for(const [id,key] of [['views','views'],['consultations','consultations'],['downloads','downloads'],['contacts','contacts']])document.querySelector(`#${id}`).textContent=number(c.summary?.[key]);document.querySelector('#outbound').textContent=number(t.outbound_tool);document.querySelector('#whatsapp').textContent=number(t.whatsapp_click);list('#pages',c.topPages);list('#items',c.topItems);list('#datasheets',c.topDatasheets);list('#sources',c.sources);list('#lines',data.topLines);list('#references',data.topReferences);list('#landings',data.topLandings);document.querySelector('#recent').innerHTML=c.recent?.length?c.recent.map(row=>`<tr><td>${new Date(row.created_at).toLocaleString('es-CO')}</td><td>${escapeHtml(row.event_type)}</td><td>${escapeHtml(row.item||'—')}</td><td>${escapeHtml(row.path||'—')}</td><td>${escapeHtml(row.source||'Directo')}</td></tr>`).join(''):'<tr><td colspan="5">Sin eventos todavía</td></tr>';draw()}
document.querySelector('#login-form').addEventListener('submit',async event=>{event.preventDefault();error.textContent='';try{const values=Object.fromEntries(new FormData(event.currentTarget));await api('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(values)});await load()}catch(e){error.textContent=e.message}});
document.querySelector('#range').addEventListener('change',event=>load(event.target.value));document.querySelector('#granularity').addEventListener('change',draw);document.querySelector('#logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()});window.addEventListener('resize',()=>currentData&&draw());api('/api/admin/session').then(()=>load()).catch(()=>{login.hidden=false;dashboard.hidden=true});
